In [1]:
import pandas as pd

In [2]:
import yaml

In [5]:
cfg=yaml.safe_load(open("../config/base.yaml"))
print(cfg)

{'data': {'root': "Italian Parkinson's Voice and speech", 'groups': ["Italian Parkinson's Voice and speech/28 People with Parkinson's disease", "Italian Parkinson's Voice and speech/22 Elderly Healthy Control"], 'target_sr': 16000, 'tasks': 'all'}, 'splits': {'type': 'group_kfold', 'n_splits': 5, 'seed': 42, 'group_by': 'speaker'}}

In [11]:
print(cfg["data"]["groups"][1])

Italian Parkinson's Voice and speech/22 Elderly Healthy Control

In [12]:
from pathlib import Path
file_codes=pd.read_excel("../"+cfg["data"]["groups"][1]+"/FILE CODES.xlsx")

In [13]:
file_codes.head(5)

   Unnamed: 0 Unnamed: 1                                         Unnamed: 2
0         NaN        NaN                                                NaN
1         NaN        NaN                                                NaN
2         NaN        NaN                                                NaN
3         NaN         B1  first reading of the phonemically balanced tex...
4         NaN         B2  second reading of the phonemically balanced te...

In [14]:
tab_3=pd.read_excel("../"+cfg["data"]["groups"][1]+"/Tab 3.xlsx")
tab_3.head(5)

,PERSON,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,TEXT 1^READING,Unnamed: 6,TEXT 2^READING,Unnamed: 8,TEXT 3^READING,Unnamed: 10
0,name,surname,sex,age,from,time1,CPS1,time2,CPS2,time3,CPS3
1,Brigida,C,F,69,Bari,57.12,9.068627,49.99,10.362072,47.11,5.964763
2,Agnese,P*,F,62,Bari,100.95,4.715206,77.26,5.940979,66.4,3.915663
3,Gilda,C*,F,65,Bari,70.87,7.309158,57.71,8.681338,43.16,6.510658
4,Michele,G,M,68,Bari,59.55,8.698573,55.08,9.331881,43.47,6.464228