In [16]:
import MetaTrader5 as mt5

In [17]:
mt5.shutdown()
connected=mt5.initialize(timeout=5000)
print(connected)
symbols=mt5.symbols_get()
print(symbols)

True

In [18]:
btc_symbols=sorted([s.name for s in symbols if "BTC" in s.name.upper()])
print(btc_symbols)

['BTCETH', 'BTCUSD', 'BTCXAU']

In [19]:
symbol="BTCUSD"
mt5.symbol_select(symbol,True)
print("Selected",symbol)

Selected BTCUSD

In [ ]:
import pandas as pd
rates=mt5.copy_rates_from_pos(symbol,mt5.TIMEFRAME_H1,,10000)
print(len(rates))

4327

In [34]:
df=pd.DataFrame(rates)
df["time"]=pd.to_datetime(df["time"],unit="s",utc=True)
df=df.sort_values("time").reset_index(drop=True)
df.head(1)

,time,open,high,low,close,tick_volume,spread,real_volume
0,2014-11-12 00:00:00+00:00,411.95,421.72,405.16,418.67,561,0,0

In [35]:
df.tail(1)

,time,open,high,low,close,tick_volume,spread,real_volume
4326,2026-09-18 00:00:00+00:00,76527.5,77572.9,76207.0,77254.1,17915,1965,0

In [ ]:
from datetime import datetime, timezone, timedelta


symbol = "BTCUSD"       
timeframe = mt5.TIMEFRAME_H1

start = datetime(2013, 1, 1, tzinfo=timezone.utc)
end = datetime.now(timezone.utc)

frames = []
current = start

while current < end:
    next_date = min(
        current + timedelta(days=30),
        end
    )

    rates = mt5.copy_rates_range(
        symbol,
        timeframe,
        current,
        next_date
    )

    if rates is not None and len(rates) > 0:
        frames.append(pd.DataFrame(rates))
        print(current.date(), "to", next_date.date(), len(rates))
    else:
        print("No data:", current.date(), mt5.last_error())

    current = next_date + timedelta(seconds=1)

if not frames:
    raise RuntimeError("No data found")

df = pd.concat(frames, ignore_index=True)

df["time"] = pd.to_datetime(
    df["time"],
    unit="s",
    utc=True
)

df = (
    df.drop_duplicates("time")
      .sort_values("time")
      .reset_index(drop=True)
)

print("Total rows:", len(df))
print("First available:", df["time"].min())
print("Last available:", df["time"].max())

df.to_csv(
    f"{symbol}_H1_from_2013.csv",
    index=False
)

print(df.head(1),df.tail(1))

2013-01-01 to 2013-01-31 1
2013-01-31 to 2013-03-02 1
2013-03-02 to 2013-04-01 1
2013-04-01 to 2013-05-01 1
2013-05-01 to 2013-05-31 1
2013-05-31 to 2013-06-30 1
2013-06-30 to 2013-07-30 1
2013-07-30 to 2013-08-29 1
2013-08-29 to 2013-09-28 1
2013-09-28 to 2013-10-28 1
2013-10-28 to 2013-11-27 1
2013-11-27 to 2013-12-27 1
2013-12-27 to 2014-01-26 1
2014-01-26 to 2014-02-25 1
2014-02-25 to 2014-03-27 1
2014-03-27 to 2014-04-26 1
2014-04-26 to 2014-05-26 1
2014-05-26 to 2014-06-25 1
2014-06-25 to 2014-07-25 1
2014-07-25 to 2014-08-24 1
2014-08-24 to 2014-09-23 1
2014-09-23 to 2014-10-23 1
2014-10-23 to 2014-11-22 1
2014-11-22 to 2014-12-22 1
2014-12-22 to 2015-01-21 1
2015-01-21 to 2015-02-20 1
2015-02-20 to 2015-03-22 1
2015-03-22 to 2015-04-21 142
2015-04-21 to 2015-05-21 720
2015-05-21 to 2015-06-20 715
2015-06-20 to 2015-07-20 719
2015-07-20 to 2015-08-19 717
2015-08-19 to 2015-09-18 720
2015-09-18 to 2015-10-18 720
2015-10-18 to 2015-11-17 720
2015-11-17 to 2015-12-17 720
2015-12-17 to 2016-01-16 708
2016-01-16 to 2016-02-15 719
2016-02-15 to 2016-03-16 695
2016-03-16 to 2016-04-15 720
2016-04-15 to 2016-05-15 719
2016-05-15 to 2016-06-14 720
2016-06-14 to 2016-07-14 720
2016-07-14 to 2016-08-13 720
2016-08-13 to 2016-09-12 719
2016-09-12 to 2016-10-12 714
2016-10-12 to 2016-11-11 720
2016-11-11 to 2016-12-11 720
2016-12-11 to 2017-01-10 718
2017-01-10 to 2017-02-09 720
2017-02-09 to 2017-03-11 720
2017-03-11 to 2017-04-10 720
2017-04-10 to 2017-05-10 720
2017-05-10 to 2017-06-09 720
2017-06-09 to 2017-07-09 720
2017-07-09 to 2017-08-08 707
2017-08-08 to 2017-09-07 720
2017-09-07 to 2017-10-07 720
2017-10-07 to 2017-11-06 720
2017-11-06 to 2017-12-06 720
2017-12-06 to 2018-01-05 720
2018-01-05 to 2018-02-04 720
2018-02-04 to 2018-03-06 720
2018-03-06 to 2018-04-05 720
2018-04-05 to 2018-05-05 720
2018-05-05 to 2018-06-04 720
2018-06-04 to 2018-07-04 720
2018-07-04 to 2018-08-03 720
2018-08-03 to 2018-09-02 720
2018-09-02 to 2018-10-02 720
2018-10-02 to 2018-11-01 720
2018-11-01 to 2018-12-01 714
2018-12-01 to 2018-12-31 720
2018-12-31 to 2019-01-30 720
2019-01-30 to 2019-03-01 720
2019-03-01 to 2019-03-31 720
2019-03-31 to 2019-04-30 720
2019-04-30 to 2019-05-30 720
2019-05-30 to 2019-06-29 720
2019-06-29 to 2019-07-29 720
2019-07-29 to 2019-08-28 720
2019-08-28 to 2019-09-27 720
2019-09-27 to 2019-10-27 720
2019-10-27 to 2019-11-26 720
2019-11-26 to 2019-12-26 720
2019-12-26 to 2020-01-25 720
2020-01-25 to 2020-02-24 720
2020-02-24 to 2020-03-25 720
2020-03-25 to 2020-04-24 720
2020-04-24 to 2020-05-24 720
2020-05-24 to 2020-06-23 720
2020-06-23 to 2020-07-23 720
2020-07-23 to 2020-08-22 720
2020-08-22 to 2020-09-21 720
2020-09-21 to 2020-10-21 720
2020-10-21 to 2020-11-20 720
2020-11-20 to 2020-12-20 708
2020-12-20 to 2021-01-19 672
2021-01-19 to 2021-02-18 720
2021-02-18 to 2021-03-20 720
2021-03-20 to 2021-04-19 720
2021-04-19 to 2021-05-19 720
2021-05-19 to 2021-06-18 720
2021-06-18 to 2021-07-18 717
2021-07-18 to 2021-08-17 720
2021-08-17 to 2021-09-16 720
2021-09-16 to 2021-10-16 720
2021-10-16 to 2021-11-15 720
2021-11-15 to 2021-12-15 720
2021-12-15 to 2022-01-14 720
2022-01-14 to 2022-02-13 720
2022-02-13 to 2022-03-15 718
2022-03-15 to 2022-04-14 720
2022-04-14 to 2022-05-14 720
2022-05-14 to 2022-06-13 720
2022-06-13 to 2022-07-13 714
2022-07-13 to 2022-08-12 714
2022-08-12 to 2022-09-11 719
2022-09-11 to 2022-10-11 720
2022-10-11 to 2022-11-10 720
2022-11-10 to 2022-12-10 719
2022-12-10 to 2023-01-09 717
2023-01-09 to 2023-02-08 720
2023-02-08 to 2023-03-10 720
2023-03-10 to 2023-04-09 711
2023-04-09 to 2023-05-09 716
2023-05-09 to 2023-06-08 717
2023-06-08 to 2023-07-08 720
2023-07-08 to 2023-08-07 720
2023-08-07 to 2023-09-06 720
2023-09-06 to 2023-10-06 720
2023-10-06 to 2023-11-05 720
2023-11-05 to 2023-12-05 720
2023-12-05 to 2024-01-04 719
2024-01-04 to 2024-02-03 720
2024-02-03 to 2024-03-04 720
2024-03-04 to 2024-04-03 720
2024-04-03 to 2024-05-03 718
2024-05-03 to 2024-06-02 720
2024-06-02 to 2024-07-02 720
2024-07-02 to 2024-08-01 720
2024-08-01 to 2024-08-31 720
2024-08-31 to 2024-09-30 720
2024-09-30 to 2024-10-30 720
2024-10-30 to 2024-11-29 720
2024-11-29 to 2024-12-29 719
2024-12-29 to 2025-01-28 720
2025-01-28 to 2025-02-27 720
2025-02-27 to 2025-03-29 720
2025-03-29 to 2025-04-28 720
2025-04-28 to 2025-05-28 720
2025-05-28 to 2025-06-27 720
2025-06-27 to 2025-07-27 720
2025-07-27 to 2025-08-26 720
2025-08-26 to 2025-09-25 720
2025-09-25 to 2025-10-25 717
2025-10-25 to 2025-11-24 720
2025-11-24 to 2025-12-24 720
2025-12-24 to 2026-01-23 720
2026-01-23 to 2026-02-22 720
2026-02-22 to 2026-03-24 720
2026-03-24 to 2026-04-23 720
2026-04-23 to 2026-05-23 720
2026-05-23 to 2026-06-22 720
2026-06-22 to 2026-07-22 720
2026-07-22 to 2026-08-21 720
2026-08-21 to 2026-09-18 676
Total rows: 99997
First available: 2015-04-15 03:00:00+00:00
Last available: 2026-09-18 04:00:00+00:00
CSV তৈরি হয়েছে